### ISSUE TITLE
BFS is O(E + V²) instead of O(E + V)

### ISSUE THREAD

**Issue by marcussimonsen** [frederikgantriis/red-scare#1]
Using list.pop(n) uses time linear in length of list.

https://github.com/frederikgantriis/red-scare/blob/5c61923547460b481cc3c4634f7c9797a8b8e450/solutions/alternate.py#L33

This results in BFS being in O(E + V²) instead of O(E + V).

**Comment by JonasUJ** [comment]
Solved by #3
